<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Atlanta 550 Pharr Road NE Suite 525Atlant_8f4c85</name>
   <tag></tag>
   <elementGuidId>74ff81d5-e2f6-471e-99b3-b81eaf342163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>33fe0f66-93f7-41d2-baf7-7625e09d296c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atlanta 550 Pharr Road NE Suite 525Atlanta, GA 30305</value>
      <webElementGuid>884a476d-be17-4aa3-a492-fd71d08ab60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 col-lg-offset-1 text-center&quot;]/p[1]</value>
      <webElementGuid>d0dc2452-bf7b-4bd0-bfb9-11e9cd8dff47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>c359a896-41ad-4b03-95e4-d3f71a6c5bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Atlanta 550 Pharr Road NE Suite 525Atlanta, GA 30305' or . = 'Atlanta 550 Pharr Road NE Suite 525Atlanta, GA 30305')]</value>
      <webElementGuid>bf3e8ab2-2a53-46f2-be36-a8687143efb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
